version: 2.1

aliases:
- &common_env
  remote: quay.io
  repo: qoqodev/telegraf

workflows:
  version: 2.1
  build:
    jobs:
    - build
  sync:
    jobs:
    - sync
    triggers:
    - schedule:
        cron: "0 0 * * *"
        filters:
          branches:
            only:
            - master
  load:
    jobs:
    - hold:
        type: approval
    - load:
        requires:
        - hold

jobs:
  build:
    environment:
      <<: *common_env
    docker:
    - image: docker:stable
    steps:
    - checkout
    - setup_remote_docker
    - run: |
        . .circleci/functions.sh
        tag=latest
        docker_login "$remote"
        docker_build "$tag"

  sync:
    environment:
      <<: *common_env
    docker:
    - image: docker:stable
    steps:
    - checkout
    - setup_remote_docker
    - run: |
        . .circleci/functions.sh
        docker_login "$remote"
        apk add -U curl grep coreutils
        sync

  load:
    environment:
      <<: *common_env
    docker:
    - image: docker:stable
    steps:
    - checkout
    - setup_remote_docker
    - run: |
        . .circleci/functions.sh
        docker_login "$remote"
        apk add -U curl
        load
